apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager-dingtalk
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    k8s-app: prometheus-alertmanager-dingtalk 
  type: "ClusterIP"
